services:
  - type: web
    name: scentryx-gas-detector
    env: node
    plan: free
    region: oregon  # or singapore for Asia
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://kenneth:radin159@scentryx.fh5hb0k.mongodb.net/scentryx?retryWrites=true&w=majority
    healthCheckPath: /health
    autoDeploy: true